/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: zigurat architecture studio (https://sketchfab.com/ziguratarchitecturestudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-luxury-villa-house-building-home-705587556d3b49dcafd8b9ab4905ced5
Title: Modern luxury villa house building home
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export function HouseModel({ src, ...props }: any) {
    const { scene } = useGLTF('/house.glb')
    return (
        <group >
            <primitive object={scene} />
        </group>
    )
}

useGLTF.preload('/house.glb')
